In [1]:
from numpy import load, save


X = load("X.npy", mmap_mode='r')


In [2]:
X_train_1 = X[:12500]



In [3]:
X_train_1 = X_train_1/255

In [4]:
save("X_train_1.npy", X_train_1)

In [5]:
from numpy import load

X_train = load("X_train_1.npy", mmap_mode = 'r+')

In [6]:
print(X_train[12499])

[[[0.12941176 0.21960784 0.09411765]
  [0.23529412 0.32156863 0.19607843]
  [0.49019608 0.57647059 0.44313725]
  ...
  [0.2627451  0.34117647 0.22745098]
  [0.36470588 0.44705882 0.3254902 ]
  [0.30196078 0.38823529 0.25882353]]

 [[0.21960784 0.29411765 0.16470588]
  [0.22352941 0.30196078 0.17254902]
  [0.44705882 0.52156863 0.39215686]
  ...
  [0.27843137 0.35294118 0.24705882]
  [0.34901961 0.42745098 0.30980392]
  [0.41568627 0.49803922 0.37254902]]

 [[0.32941176 0.39607843 0.26666667]
  [0.51372549 0.58039216 0.44705882]
  [0.44313725 0.50588235 0.37254902]
  ...
  [0.31372549 0.38431373 0.29019608]
  [0.27058824 0.34509804 0.24313725]
  [0.3254902  0.4        0.29019608]]

 ...

 [[0.40784314 0.45882353 0.3254902 ]
  [0.41568627 0.4627451  0.3372549 ]
  [0.44705882 0.49019608 0.37647059]
  ...
  [0.56470588 0.59607843 0.60784314]
  [0.60392157 0.63921569 0.64705882]
  [0.64705882 0.68627451 0.69803922]]

 [[0.32156863 0.40784314 0.28235294]
  [0.24705882 0.3254902  0.21176471]


In [2]:
X_train_2 = X[12501:-1]


In [3]:
X_train_2 = X_train_2/255

In [ ]:
save("X_train_2.npy", X_train_2)